function A = affineMetricUpgradeCoefficients(in1)
%AFFINEMETRICUPGRADECOEFFICIENTS
%    A = AFFINEMETRICUPGRADECOEFFICIENTS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    12-Nov-2016 20:25:34

M1_1 = in1(1);
M1_2 = in1(3);
M1_3 = in1(5);
M2_1 = in1(2);
M2_2 = in1(4);
M2_3 = in1(6);
A = reshape([M1_1.^2,M1_1.*M2_1,M2_1.^2,M1_1.*M1_2.*2.0,M1_1.*M2_2+M1_2.*M2_1,M2_1.*M2_2.*2.0,M1_1.*M1_3.*2.0,M1_1.*M2_3+M1_3.*M2_1,M2_1.*M2_3.*2.0,M1_2.^2,M1_2.*M2_2,M2_2.^2,M1_2.*M1_3.*2.0,M1_2.*M2_3+M1_3.*M2_2,M2_2.*M2_3.*2.0,M1_3.^2,M1_3.*M2_3,M2_3.^2],[3,6]);
