function somLambda_geodFun_test()
x0=struct('lambda',rand(8,1),...
    'R',rot_randn([],[],8),...
    'T',randn(3,8));

vx0=struct('lambda',rand(8,1),...
    'R',eye3d(3,3,8),...
    'T',zeros(3,8));

[xt,dxt]=somLambda_geodFun(x0,vx0);

funCheckDer(@(t) xt(t).lambda,@(t) dxt(t).lambda)
