function evalTryAndMail(cmd)

pid=getpid();
hostname=gethostname();
hostname=hostname(1:end-1); %Remove newline at the end
subject=['Automatic message from Matlab with pid ' num2str(pid) ' on ' hostname];

tic
try
    eval(cmd)
catch ME
    sendmail('tron@seas.upenn.edu',subject,['Dear human,' 10 ...
        'There was an error during the execution of the following command:' 10 ...
        cmd 10 ...
        'The message was:' 10 ...
        ME.message 10 ...
        10 ...
        'But remember, DON''T PANIC!' 10 ...
        10 ...
        'Eddie''s your ship computer' ...
        ])
    rethrow(ME)
end
t=toc;
sendmail('tron@seas.upenn.edu',subject,['Greetings from here!' 10 ...
    'The execution of the following command:' 10 ...
    cmd 10 ...
    'has successfully finished. It took me ' num2str(t) ' seconds. Have a nice day!' 10 ...
    10 ...
    'Eddie''s your ship computer' ...
    ])
