%function testNetworkDisplayImages(t_node)
%Displays the images of the points generated by the function testNetworkProjectImages
%
% See also testNetworkProjectImages
%

%%AUTORIGHTS%%

function testNetworkDisplayImages(t_node)
structType=testNetworkDetectStructType(t_node);
N=testNetworkGetNumberOfNodes(t_node);
NCols=4;            %number of columns of subplots
NRows=ceil(N/4);    %number of rows of subplots


%plot projected images for each node
for iNode=1:N
    subplot(NRows,NCols,iNode)
    switch structType
        case 'single'
            ximage=t_node.ximage{iNode};
        case 'array'
            ximage=t_node(iNode).ximage;
    end
    plot(ximage(1,:),ximage(2,:),'k.')
    axis equal
    axis([-2 2 -2 2])
end
    