function errors=multiCalibration_errorsCompute(posesRelative,correspondences)
NCorrespondences=length(correspondences);
errors=cell(NCorrespondences,1);
for iCorrespondence=1:NCorrespondences
    cCurrent=correspondences{iCorrespondence};
    switch cCurrent.type
        case 'plane-plane'
            [errors{iCorrespondence}.rot,errors{iCorrespondence}.transl]=...
                poseEstimationFromNormalsDistancesResidualsG(...
                posesRelative(iCorrespondence).G,...
                cCurrent.n1,cCurrent.d1,...
                cCurrent.n2,cCurrent.d2);
        case 'plane-point'
            errors{iCorrespondence}=...
                poseEstimationFromNormalsPointsResidualsG(...
                posesRelative(iCorrespondence).G,...
                cCurrent.n1,cCurrent.d1,...
                cCurrent.x22D);
    end
end
