function [Gt,vGt]=rot3r3_geodFun(G0,v)
N=size(G0,3);
[R0,T0]=G2RT(G0);
vR=rot_hat(R0,v(1:3,:));
vT=v(4:6,:);
[Rt,vt]=rot_geodFun(R0,vR);
Tt=@(t) T0+t*vT;
wt=@(t) vT;
Gt=@(t) RT2G(Rt(t),Tt(t));
vGt=@(t) [vt(t) permute(wt(t),[1 3 2]); zeros(1,4,N)];
