function gradPhiVec=bearingNetworkCostRotationVisibilityPairGradient(Ri,Rj,yij,nyij,y0,funs)
gradPhiVeciji=bearingCostRotationVisibilityGradient(Ri,yij,nyij,y0,funs);
gradPhiVecjii=-[0;gradPhiVeciji(2:3)];
gradPhiVecjij=bearingCostRotationVisibilityGradient(Rj,-yij,nyij,y0,funs);
gradPhiVecijj=-[0;gradPhiVecjij(2:3)];
%gradPhiVecjij=bearingCostRotationVisibilityGradient(Rj,-yij,nyij,y0,funs);
%gradPhiVecijj=bearingCostRotationVisibilityGradient(Rj,yij,nyij,y0,funs);
%gradPhiVec=[gradPhiVeciji gradPhiVecjii];
%gradPhiVec=[gradPhiVecijj gradPhiVecjij];
gradPhiVec=[gradPhiVeciji+gradPhiVecijj gradPhiVecjii+gradPhiVecjij];
