function [allMethods,allNames]=sfm_poseCombine_testGetAllMethods()
list={
    {'optsGlobal',{'Spectral'}},'Lin. Trace'
    {'optsGlobal',{'Spectral','Normalize'}}, 'Lin. Trace Norm.'
    {'optsGlobal',{'Laplacian'}}, 'Lin. L2'
    {'optsGlobal',{'Laplacian','normalize'}}, 'Lin. L2 Norm.'
    {'optsGlobal',{'Spectral','Adjust'}}, 'Lin. Trace Upg.'
    {'optsGlobal',{'Laplacian','Adjust'}}, 'Lin. L2 Upg.'
    {'optsGlobal',{'Laplacian','normalize','Adjust'}}, 'Lin. L2 Upg. Norm.'
    {'optsGlobal',{'SDP'}}, 'SDP Trace'
    {'optsGlobal',{'SDP','optsLowRank',{'spectrahedral'}}}, 'SDP Trace Convex Hull'
    {'optsGlobal',{'ALM'}}, 'Nuc. Norm L2'
    {'optsGlobal',{'SDP','Adjust'}}, 'SDP Trace Upg.'
    {'optsGlobal',{'ALM','Adjust'}}, 'Nuc. Norm L2 Upg.'
    {'optsGlobal',{'ALM','optsLowRank',{'innerProj',false}}}, 'Nuc. Norm L2 No proj.'
    {'optsGlobal',{'ALM','optsLowRank',{'criterion','l1'}}}, 'Nuc. Norm L1'
    {'optsGlobal',{'ALM','optsLowRank',{'criterion','l1','innerProj',false}}}, 'Nuc. Norm L1 No proj.'
    {'optsGlobal',{'ALM','optsLowRank',{'criterion','l12'}}}, 'Nuc. Norm L12'
    {'optsGlobal',{'ALM','optsLowRank',{'criterion','l12','innerProj',false}}}, 'Nuc. Norm L12 No proj.'
    {'inferenceOutliers','optsGlobal',{'Spectral'}}, 'Infer. + Lin. Trace'
    {'inferenceOutliers','optsGlobal',{'SDP'}}, 'Infer. + SDP Trace'
    {'inferenceOutliers','optsGlobal',{'ALM'}}, 'Infer. + Nuc. Norm L2'
    {'inferenceOutliers','optsGlobal',{'ALM','optsLowRank',{'criterion','l1'}}}, 'Infer. + Nuc. Norm L1'
    {'inferenceOutliers','optsGlobal',{'ALM','optsLowRank',{'criterion','l12'}}}, 'Infer. + Nuc. Norm L12'
    {'localRefine','optsGlobal',{'Spectral'}}, 'Lin. Trace + Refin.'
    {'localRefine','optsGlobal',{'SDP'}}, 'SDP Trace + Refin.'
    {'localRefine','optsGlobal',{'ALM'}}, 'Nuc. Norm L2 + Refin.'
    {'localRefine','optsGlobal',{'ALM','optsLowRank',{'criterion','l1'}}}, 'Nuc. Norm L1 + Refin.'
    {'localRefine','optsGlobal',{'ALM','optsLowRank',{'criterion','l12'}}}, 'Nuc. Norm L12 + Refin.'
    {'localRefine','optsLocal',{'method','Weiszfeld'},'optsGlobal',{'Spectral'}}, 'Lin. Trace + Weis. Refin.'
    {'localRefine','optsLocal',{'method','Weiszfeld'},'optsGlobal',{'SDP'}}, 'SDP Trace + Weis. Refin.'
    {'localRefine','optsLocal',{'method','Weiszfeld'},'optsGlobal',{'ALM'}}, 'Nuc. Norm L2  + Weis. Refin.'
    {'localRefine','optsLocal',{'method','Weiszfeld'},'optsGlobal',{'ALM','optsLowRank',{'criterion','l1'}}}, 'Nuc. Norm L1  + Weis. Refin.'
    {'localRefine','optsLocal',{'method','Weiszfeld'},'optsGlobal',{'ALM','optsLowRank',{'criterion','l12'}}}, 'Nuc. Norm L12  + Weis. Refin.'
    {'inferenceOutliers','localRefine','optsGlobal',{'Spectral'}}, 'Infer. + Lin. Trace + Refin.'
    {'inferenceOutliers','localRefine','optsGlobal',{'SDP'}}, 'Infer. + SDP Trace + Refin.'
    {'inferenceOutliers','localRefine','optsGlobal',{'ALM'}}, 'Infer. + Nuc. Norm L2 + Refin.'
    {'inferenceOutliers','localRefine','optsGlobal',{'ALM','optsLowRank',{'criterion','l1'}}}, 'Infer. + Nuc. Norm L1 + Refin.'
    {'inferenceOutliers','localRefine','optsGlobal',{'ALM','optsLowRank',{'criterion','l12'}}}, 'Infer. + Nuc. Norm L12 + Refin.'
    {'optsGlobal',{'sdp','projectBeforeFactorization'}}, 'SDP Trace With proj.'
    {'optsGlobal',{'alm','optsLowRank',{'criterion','l1','optsOptimizer',{'lowrankprior','SDP'}}}}, 'SDP L1',
    {'optsGlobal',{'alm','optsLowRank',{'criterion','l1','innerProj',false,'optsOptimizer',{'lowrankprior','SDP'}}}}, 'SDP L1 No proj.'
    {'optsGlobal',{'alm','optsLowRank',{'criterion','l12','optsOptimizer',{'lowrankprior','SDP'}}}}, 'SDP L12',
    {'optsGlobal',{'alm','optsLowRank',{'criterion','l12','innerProj',false,'optsOptimizer',{'lowrankprior','SDP'}}}}, 'SDP L12 No proj.'
    };
allMethods=list(:,1);
allNames=list(:,2);
